
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
      contents: 'read'
      id-token: 'write'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run CI
      run: npm ci
      working-directory: finPath
    - name: Build
      run: npm run build --if-present
      working-directory: finPath
   # - name: Test
    #  run: npm test
     # working-directory: finPath
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: `google-github-actions/auth@v0.4.0'
      with:
      credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
   # - id: 'auth'
     # uses: 'google-github-actions/auth@v2'
      #env:
       # GOOGLE_CREDENTIALS: ${{secrets.GCP_SA_KEY}}
      #with:
        #workload_identity_provider: 'projects/416228969428/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        #auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        #service_account: 'terraform-sa-finpath@finpath-430717.iam.gserviceaccount.com'
      
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'FinPath\finPath\.nuxt\dist\server'
        destination: 'gs://finpath-spa'
 
